# Netlify configuration for Next.js monorepo

[build]
  # Build command from root of monorepo
  command = "npm run build"

  # Publish directory - Next.js app build output
  publish = "apps/web/.next"

  # Base directory - stay at monorepo root
  base = "."

[build.environment]
  # Disable Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"

  # Node version
  NODE_VERSION = "18"

# Essential plugin for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect root to French locale by default
[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache control for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"